server:
  port: 8090
#jpa
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
#logging
logging:
  file:
    name: my_dev_app.log
    path: logs/
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG